CB-14883 mount-instance-storage service no longer mounts volumes twice
Added a check to skip the script, of all volumes are mounted already.

diff --git a/orchestrator-salt/src/main/resources/salt/salt/disks/service/scripts/mount-instance-storage.j2 b/orchestrator-salt/src/main/resources/salt/salt/disks/service/scripts/mount-instance-storage.j2
--- a/orchestrator-salt/src/main/resources/salt/salt/disks/service/scripts/mount-instance-storage.j2
+++ b/orchestrator-salt/src/main/resources/salt/salt/disks/service/scripts/mount-instance-storage.j2
@@ -6,6 +6,7 @@ MOUNT_PATH="{{ (salt['pillar.get']('mount')[salt['grains.get']('fqdn')])['mount_
 TEMPORARY_STORAGE="{{ (salt['pillar.get']('mount')[salt['grains.get']('fqdn')])['temporary_storage'] }}"
 CLOUD_PLATFORM="{{ (salt['pillar.get']('mount')[salt['grains.get']('fqdn')])['cloud_platform'] }}"
 LOG_FILE="/var/log/mount-instance-storage.log"
+SEMAPHORE_FILE="/var/cb-mount-instance-storage-dryrun"
 FS_TYPE=ext4
 
 format_disks_if_unformatted() {
@@ -53,6 +54,8 @@ mount_all_sequential() {
     log $LOG_FILE "mounting storage devices ${device_uuids_arr[@]}"
     local hadoop_fs_dir_counter=1
     if [[ $MOUNT_PATH = *"ephfs"* ]]; then
+      hadoop_fs_dir_counter=1
+    elif [[ $TEMPORARY_STORAGE = "EPHEMERAL_VOLUMES_ONLY" ]]; then
       hadoop_fs_dir_counter=1
     else
       declare -a mountpoints_arr
@@ -184,9 +187,32 @@ find_format_and_mount_ephemeral_storage_aws() {
     return $((return_code))
 }
 
+semaphore_file_exists() {
+    local log_file=$1
+    if [ ! -f "$SEMAPHORE_FILE" ]; then
+        log $log_file "semaphore file $SEMAPHORE_FILE missing, cannot proceed. Exiting"
+        exit 1
+    fi
+}
+
+is_there_a_volume_to_mount() {
+    not_mounted_volume_names=$(lsblk_command | grep -v / | grep ^[a-z] | cut -f1 -d' ')
+    root_disk=$(get_root_disk)
+    for volume in $not_mounted_volume_names; do
+      uuid=$(get_disk_uuid "/dev/$volume")
+      if [[ $root_disk != "/dev/$volume" && "$uuid" = ""  ]]; then
+        log $LOG_FILE "Found at least one volume which is not mounted."
+        return
+      fi
+    done
+    log $LOG_FILE "All volumes are mounted. Exiting"
+    exit_with_code $LOG_FILE 0 "script 'mount-instance-storage' ended"
+}
+
 main () {
     log $LOG_FILE "script 'instance-storage-format-and-mount' starts"
     sleep 1
+
 
     if [[ "$CLOUD_PLATFORM" == "AZURE" && "$TEMPORARY_STORAGE" == "EPHEMERAL_VOLUMES" ]]; then
         log $LOG_FILE "Starting to remount Azure temporary storage device"
@@ -196,6 +222,7 @@ main () {
         [[ ! $return_code -eq 0 ]] && exit_with_code $LOG_FILE $return_code "Error remounting Azure temporary storage device"
     elif [[ "$CLOUD_PLATFORM" == "AWS" ]]; then
         log $LOG_FILE "Starting to remount AWS ephemeral devices"
+        is_there_a_volume_to_mount
         find_format_and_mount_ephemeral_storage_aws
         return_code=$?
         log $LOG_FILE result of remounting AWS ephemeral devices: $return_code
